config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'snows/niigata' => 'snows#niigata'
  get 'snows/nagano' => 'snows#nagano'
  get 'snows/gunnma' => 'snows#gunnma'

  resources :snows
  root 'snows#index'

  resources :users, :only => [:index, :show]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show]
 
  get 'snows/new/:category' => 'snows#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/lecture.rb
class Lecture < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
end

app/models/snow.rb
class Snow < ApplicationRecord

    belongs_to :user
    mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :snows, dependent: :destroy
         validates :name, presence: true 
         validates :profile, length: { maximum: 200 } 
         has_many :messages, dependent: :destroy
         has_many :entries, dependent: :destroy
         mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :authenticate_user!

    def create
      if Entry.where(user_id: current_user.id, room_id: params[:message][:room_id]).present?
        @message = Message.new(message_params)
        if @message.save
            redirect_to "/rooms/#{@message.room_id}"
        end
      else
        redirect_back(fallback_location: root_path)
      end
    end

    private 
    def message_params
        params.require(:message).permit(:user_id, :body, :room_id).merge(user_id: current_user.id)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    @room = Room.create
    Entry.create(room_id: @room.id, user_id: current_user.id)
    Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages.all
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/snows_controller.rb
class SnowsController < ApplicationController

    before_action :authenticate_user!, only: [:new, :create]

    def new
        @Snow = Snow.new
        @category = params[:category]
    end
    

    def create


    

        snow = Snow.new(snow_params)
        snow.user_id = current_user.id

        if snow.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
    end
    

    def niigata
        @niigatas = Snow.where(category:"niigata")
    end
      def nagano
        @naganos = Snow.where(category:"nagano")
      end
    
      def gunnma
        @gunnmas = Snow.where(category:"gunnma")
      end



    def index
        @snows = Snow.all
    end

    def show
        @Snow = Snow.find(params[:id])
    end

    def edit
        @Snow = Snow.find(params[:id])
    end

    def update
        snow = Snow.find(params[:id])
       
        if snow.update(snow_params)
          redirect_to :action => "show", :id => snow.id
        else
          redirect_to :action => "new"
        end
    end

    def destroy
        snow = Snow.find(params[:id])
        snow.destroy
        redirect_to action: :index
    end


   


    private

      def snow_params


        params.require(:snow).permit(:spot, :address, :image, :hp, :telephone, :lat, :lng, :overall, :category)


      end

    end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
  def index
    @users=User.all
  end

  def show
    @user=User.find(params[:id])
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
      @msg ="他のユーザーとDMしてみよう！"
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end

      if @isRoom != true
        @room = Room.new
        @entry = Entry.new
      end

    end
  end
end

app/controllers/whites_controller.rb
class WhitesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/snows_helper.rb
module SnowsHelper

  def  getPercent(number) 
    if number.present?
      calPercent = number/5.to_f * 100
      # calPercent = number/10.to_f * 100
      #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
      percent = calPercent.round
      #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
      return percent.to_s
    else
      return 0
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/whites_helper.rb
module WhitesHelper
end

app/views/rooms/show.html.erb
<div class="dmMain">
    <div class="rooms-show-name">
        <% @entries.each do |e| %>
            <h3><strong><a href="/users/<%= e.user.id %>"><%= e.user.name%></a></strong></h3>
        <% end %>
    </div>
    <% @messages.each do |m| %>
        <small><%= m.user.name %>さん</small><hr>
        <h4><%= m.body %></h4>
    <% end %>

    
        <%= form_for @message do |f| %>
            <div class="room-show-dmbox">
                <div class="room-show-text">
                    <%= f.text_field :body, :placeholder => "メッセージを入力して下さい" , :size => 100 %>
                    <%= f.hidden_field :room_id, :value => @room.id %>
                </div>
            </div>
            <div class="room-show-buttoncenter">
                <div class="room-show-button">
                    <%= f.submit "送信する" %>
                </div>
            </div>
        <% end %>
    </div>
</div>

<div class="room-show-link">
    <div class="room-show-alluserlink">
        <%= link_to "ALL USERS", users_path %>
    </div>
    <div class="room-show-homelink">
        <%= link_to "HOME", snows_path %>
    </div>
</div>

<style>
.rooms-show-name{
    text-align: center ;
}
.user-in{
    text-align:center;
    border:1px solid darkgray;
    background-color:gainsboro;
}
.dmMain{
    padding:30px;
    border:1px solid darkgray;
    background-color:gainsboro;
    width: 80% ;
    margin: 0 auto ;
    margin-top: 70px;
}
</style>

app/views/snows/edit.html.erb
<div class="snow-edit">
  <div class="snow-edit-backimage">
    <div class="snow-edit-flame">
        <%= form_for @Snow do |f| %>
            <div class="snow-edit-image-flex">
                <div class="snow-edit-image">
                    <label class="snow-edit-text-image">画像</label>
                    <%= f.file_field :image %>
                </div>
                <div id="edit-image"></div>
            </div>

            <div class="snow-edit-spot">
                <label class="snow-edit-text-spot">スキー場</label>
                <%= f.text_field :spot, :size => 30 %>
            </div>

            <p class="snow-edit-text-star">総合評価</p>
                <div class="snow-edit-star">
                    <%= f.radio_button :overall, 5 ,id: 'star1'%>
                    <label for="star1"><span class="text">最高</span>★</label>

                    <%= f.radio_button :overall, 4 ,id: 'star2'%>
                    <label for="star2"><span class="text">良い</span>★</label>

                    <%= f.radio_button :overall, 3 ,id: 'star3'%>
                    <label for="star3"><span class="text">普通</span>★</label>

                    <%= f.radio_button :overall, 2 ,id: 'star4'%>
                    <label for="star4"><span class="text">悪い</span>★</label>

                    <%= f.radio_button :overall, 1 ,id: 'star5'%>
                    <label for="star5"><span class="text">最悪</span>★</label>
                </div>
            
            <div class="snow-edit-hp">
                <label class="snow-edit-text-hp">HPリンク</label>
                <%= f.text_field :hp, :size => 30 %>
            </div>

            <div class="snow-edit-telephone">
                <label class="snow-edit-text-telephone">電話番号</label>
                <%= f.text_field :telephone, :size => 30 %>
            </div>

            <div class="snow-edit-address">
                <label class="snow-edit-text-address">住所</label>
                <%= f.text_field :address, :size => 30 %>
            </div>

            <div class="snow-edit-ken">
                <p class="snow-edit-text-ken">県名</p> 
                <div class="snow-edit-ken-select">
                    <%= f.select :category, [["新潟", "niigata"], ["長野", "nagano"], ["群馬", "gunnma"]], include_blank: "どの投稿？" %>
                </div>
            </div>
    </div>
    <div class="snow-edit-submit">
        <%= f.submit "EDIT" %>
    </div>
  </div>
            
        <% end %>
 <div class="snow-edit-link">
    <%= link_to "HOME", snows_path %>
 </div>
</div>

app/views/snows/gunnma.html.erb
<h1>群馬のスキー場やで</h1>
<div class="snows-container">
<% @gunnmas.each do |t| %>
    <% if t.category == "gunnma" %> 
    <div class="snow-block">
    <p><%= image_tag t.image_url, size: "250x200" if t.image? %></p>
    </br>
    <div class="snow-index-textbox">
      <%= t.spot %>
      </br>
      <span class="star-rating">
      <span class="star-rating-front" style="width: <%= getPercent(t.overall) %>%;">★★★★★</span>
      <span class="star-rating-back">★★★★★</span>
      </span> 
      </br>
      <%= t.hp %>
      </br>
      <%= t.telephone %>
      </br>
      <%= t.address %>
     
      <div>
    </div>
    </div>
    </div>
    <% end %>
    <% end %>
    </div>
    </div>

  <%= link_to "一覧に戻る", snows_path %>

app/views/snows/index.html.erb
<div class="img-frame">
<div class="img-01"></div>
<div class="img-02"></div>
<div class="img-03"></div>
</div>


<div class="snows-container">
  <% @snows.each do |t| %>
    <div class="snow-block">
    <p><%= image_tag t.image_url, size: "250x200" if t.image? %></p>
    </br>
    <div class="snow-index-textbox">
      <%= t.spot %>
      </br>
      <span class="star-rating">
      <span class="star-rating-front" style="width: <%= getPercent(t.overall) %>%;">★★★★★</span>
      <span class="star-rating-back">★★★★★</span>
      </span> 
      </br>
      <%= t.hp %>
      </br>
      <%= t.telephone %>
      </br>
      <%= t.address %>
      <div>
    </div>
    </div>

  <div class="snow-index-showlink">
    <%= link_to "SHOW", snow_path(t.id) %>
  </div>

  <div class="snow-index-editlink">
    <%= link_to "EDIT", edit_snow_path(t.id) %>
    </div>

    <div class="snow-index-delete">
    <%= button_to "DELETE", snow_path(t.id), method: :delete %>
    
    </div>
    </div>
  <% end %>
  </div>
  </div>

  <div id='map'></div>

<style>
#map {
  height: 600px;
  width: 100%;
}
</style>

<!-- js部分 -->
<script>
    function initMap() {

      //初期表示位置
      let latlng = new google.maps.LatLng(38.60, 139.5);
      //デザイン
      let styles = [
           {
            stylers: [
             { "saturation": 0 },
             { "lightness": 0 }
            ]
           }
          ];

          


      let map = new google.maps.Map(document.getElementById('map'), {
          zoom: 5.5,
          styles: styles,
          center: latlng
      });
      let transitLayer = new google.maps.TransitLayer();
      transitLayer.setMap(map);

//複数マーカー ここから
      <% @snows.each do |t|%>
        ( function() { 
          let markerLatLng = { lat: <%= t.lat %>, lng: <%= t.lng %> }; // 緯度経度のデータ作成
          let marker = new google.maps.Marker({ 
            position: markerLatLng, 
            map: map 
          });
//マーカーをクリックしたとき、詳細情報を表示
          let infowindow = new google.maps.InfoWindow({
            position: markerLatLng,
            content: "<a href='<%= snow_url(t.id) %>' target='_blank'><%= t.spot %></a>"
          }); //ここで詳細ページへのリンクを表示させる
          marker.addListener('click', function() {
            infowindow.open(map, marker);
          });

       })();
      <% end %>
      //複数マーカー ここまで  
  }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCeGD507tfHw3zLYsclweUqIY9awizjsvc&callback=initMap" async defer></script>

app/views/snows/nagano.html.erb
<h1>長野のスキー場やで</h1>
<div class="snows-container">
<% @naganos.each do |t| %>
    <% if t.category == "nagano" %>  
    <div class="snow-block">
    <p><%= image_tag t.image_url, size: "250x200" if t.image? %></p>
    </br>
    <div class="snow-index-textbox">
      <%= t.spot %>
      </br>
      <span class="star-rating">
      <span class="star-rating-front" style="width: <%= getPercent(t.overall) %>%;">★★★★★</span>
      <span class="star-rating-back">★★★★★</span>
      </span> 
      </br>
      <%= t.hp %>
      </br>
      <%= t.telephone %>
      </br>
      <%= t.address %>
     
      <div>
    </div>
    </div>
    </div>
    <% end %>
    <% end %>
    </div>
    </div>

  <%= link_to "一覧に戻る", snows_path %>

app/views/snows/new.html.erb
<div class="snow-new">
  <div class="snow-new-backimage">
    <div class="snow-new-flame">
    <%= form_for @Snow do |f| %>
      <div class="snow-new-image-flex">
        <div class="snow-new-image">
          <label class="snow-new-text-image">画像</label>
          <%= f.file_field :image %>
        </div>
        <div id="new-image"></div>
      </div>
        
      <div class="snow-new-spot">
      <label class="snow-new-text-spot">スキー場</label>
            <%= f.text_field :spot, :size => 30 %>
      </div>

      <p class="snow-new-text-star">総合評価</p>
        <div class="snow-new-star">
        <%= f.radio_button :overall, 5 ,id: 'star1'%>
        <label for="star1"><span class="text">最高</span>★</label>

        <%= f.radio_button :overall, 4 ,id: 'star2'%>
        <label for="star2"><span class="text">良い</span>★</label>

        <%= f.radio_button :overall, 3 ,id: 'star3'%>
        <label for="star3"><span class="text">普通</span>★</label>

        <%= f.radio_button :overall, 2 ,id: 'star4'%>
        <label for="star4"><span class="text">悪い</span>★</label>

        <%= f.radio_button :overall, 1 ,id: 'star5'%>
        <label for="star5"><span class="text">最悪</span>★</label>
      </div>

      <div class="snow-new-hp">
      <label class="snow-new-text-hp">HPリンク</label>
        <%= f.text_field :hp, :size => 30 %>
      </div>

      <div class="snow-new-telephone">
      <label class="snow-new-text-telephone">電話番号</label>
        <%= f.text_field :telephone, :size => 30 %>
      </div>

      <div class="snow-new-address">
      <label class="snow-new-text-address">住所</label>
        <%= f.text_field :address, :size => 30 %>
      </div>
        
    <div class="snow-new-ken">
      <p class="snow-new-text-ken">県名</p> 
        <div class="snow-new-ken-select">
        <%= f.select :category, [["新潟", "niigata"], ["長野", "nagano"], ["群馬", "gunnma"]], include_blank: "どの投稿？" %>
        </div>
    </div>
      



      <div class="snow-new-ido">
      <label class="snow-new-text-ido">緯度</label>
        <%= f.text_field :lat,:value =>"緯度", id: :lat %>
      </div>
        
      <div class="snow-new-keido">
      <label class="snow-new-text-keido">緯度</label>
        <%= f.text_field :lng,:value =>"経度", id: :lng %>
      </div>
    </div>


    <div class="snow-new-submit">
      <%= f.submit "POST" %>
    </div>
    <% end %>
  </div>

  <div class="snow-new-googlemap">
    <h2>Map</h2>
  <div class="snow-new-googlemap-search">
    <input id="address" type="textbox" value="GeekSalon">
    <input type="button" value="検索" onclick="codeAddress()">
  </div>
    <p class="snow-new-googlemap-p">マーカーをドラック＆ドロップで位置の調整ができます。<p>
    <div id='map'></div>
  </div>

    <style>
    #map {
      margin: 0 auto;
      height: 600px;
      width: 800px;
    }
    </style>

    <script>
    //初期マップの設定
    let map
    let marker
    function initMap(){
      geocoder = new google.maps.Geocoder()

      map = new google.maps.Map(document.getElementById('map'), {
        center:  {lat: 35.6803997, lng:139.7690174},  //東京
        zoom: 15,
        
      });
    }

    //検索後のマップ作成
    let geocoder
    let aft
    function codeAddress(){
      let inputAddress = document.getElementById('address').value;
      geocoder.geocode( { 'address': inputAddress}, function(results, status) {
        if (status == 'OK') {
            //マーカーが複数できないようにする
            if (aft == true){
                marker.setMap(null);
            }

            //新しくマーカーを作成する
            map.setCenter(results[0].geometry.location);
                marker = new google.maps.Marker({
                map: map,
                position: results[0].geometry.location,
                draggable: true	// ドラッグ可能にする
            });

            //二度目以降か判断
            aft = true

            //検索した時に緯度経度を入力する
            document.getElementById('lat').value = results[0].geometry.location.lat();
            document.getElementById('lng').value = results[0].geometry.location.lng();

            // マーカーのドロップ（ドラッグ終了）時のイベント
            google.maps.event.addListener( marker, 'dragend', function(ev){
                // イベントの引数evの、プロパティ.latLngが緯度経度
                document.getElementById('lat').value = ev.latLng.lat();
                document.getElementById('lng').value = ev.latLng.lng();
            });
        } else {
          alert('該当する結果がありませんでした：' + status);
        }
      });   
    }

    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCeGD507tfHw3zLYsclweUqIY9awizjsvc&callback=initMap" async defer></script>

<div class="snow-new-link">
  <%= link_to "HOME", snows_path %>
</div>

</div>

app/views/snows/niigata.html.erb
<h1>新潟のスキー場やで</h1>
<div class="snows-container">
<% @niigatas.each do |t| %>
    <% if t.category == "niigata" %>  
    <div class="snow-block">
    <p><%= image_tag t.image_url, size: "250x200" if t.image? %></p>
    </br>
    <div class="snow-index-textbox">
      <%= t.spot %>
      </br>
      <span class="star-rating">
      <span class="star-rating-front" style="width: <%= getPercent(t.overall) %>%;">★★★★★</span>
      <span class="star-rating-back">★★★★★</span>
      </span> 
      </br>
      <%= t.hp %>
      </br>
      <%= t.telephone %>
      </br>
      <%= t.address %>
      <div>
    </div>
    </div>
    </div>
    <% end %>
    <% end %>
    </div>
    </div>
    


  <%= link_to "一覧に戻る", snows_path %>

app/views/snows/show.html.erb
<div class="snow-show-background">
  <div class="snow-show">
    <p class="snow-show-image">
      <%= image_tag @Snow.image_url, size: "250x200" if @Snow.image? %>
    </p>

    <div class="snow-edit-textbox">
      <p class="snow-show-spot">
        <%= @Snow.spot %>
      </p>
      
      <span class="snow-show-star">
        <span class="star-rating-front" style="width: <%= getPercent(@Snow.overall) %>%;">★★★★★</span>
        <span class="star-rating-back">★★★★★</span>
      </span> 

      <p class="snow-show-hp">
        <%= @Snow.hp %>
      </p>

      <p class="snow-show-telephone">
        <%= @Snow.telephone %>
      </p>

      <p class="snow-show-address">
        <%= @Snow.address %>
      </p>
    </div>

    <div class="snow-show-editlink">
      <%= link_to "TO EDIT", edit_snow_path(@Snow.id) %>
    </div>
  </div>

  <div class="snow-show-indexlink">
    <%= link_to "HOME", snows_path %>
  </div>
</div>