config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'snows/niigata' => 'snows#niigata'
  get 'snows/nagano' => 'snows#nagano'
  get 'snows/gunnma' => 'snows#gunnma'

  resources :snows
  root 'snows#index'

  resources :users, :only => [:index, :show]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show]
 
  get 'snows/new/:category' => 'snows#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/lecture.rb
class Lecture < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
end

app/models/snow.rb
class Snow < ApplicationRecord

    belongs_to :user
    mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :snows, dependent: :destroy
         validates :name, presence: true 
         validates :profile, length: { maximum: 200 } 
         has_many :messages, dependent: :destroy
         has_many :entries, dependent: :destroy
         mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :authenticate_user!

    def create
      if Entry.where(user_id: current_user.id, room_id: params[:message][:room_id]).present?
        @message = Message.new(message_params)
        if @message.save
            redirect_to "/rooms/#{@message.room_id}"
        end
      else
        redirect_back(fallback_location: root_path)
      end
    end

    private 
    def message_params
        params.require(:message).permit(:user_id, :body, :room_id).merge(user_id: current_user.id)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    @room = Room.create
    Entry.create(room_id: @room.id, user_id: current_user.id)
    Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages.all
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/snows_controller.rb
class SnowsController < ApplicationController

    before_action :authenticate_user!, only: [:new, :create]

    def new
        @Snow = Snow.new
        @category = params[:category]
    end
    

    def create


    

        snow = Snow.new(snow_params)
        snow.user_id = current_user.id

        if snow.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
    end
    

    def niigata
        @niigatas = Snow.where(category:"niigata")
    end
      def nagano
        @naganos = Snow.where(category:"nagano")
      end
    
      def gunnma
        @gunnmas = Snow.where(category:"gunnma")
      end



    def index
        @snows = Snow.all
    end

    def show
        @Snow = Snow.find(params[:id])
    end

    def edit
        @Snow = Snow.find(params[:id])
    end

    def update
        snow = Snow.find(params[:id])
       
        if snow.update(snow_params)
          redirect_to :action => "show", :id => snow.id
        else
          redirect_to :action => "new"
        end
    end

    def destroy
        snow = Snow.find(params[:id])
        snow.destroy
        redirect_to action: :index
    end


   


    private

      def snow_params


        params.require(:snow).permit(:spot, :address, :image, :hp, :telephone, :lat, :lng, :overall, :category)


      end

    end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
  def index
    @users=User.all
  end

  def show
    @user=User.find(params[:id])
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
      @msg ="他のユーザーとDMしてみよう！"
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end

      if @isRoom != true
        @room = Room.new
        @entry = Entry.new
      end

    end
  end
end

app/controllers/whites_controller.rb
class WhitesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/snows_helper.rb
module SnowsHelper

  def  getPercent(number) 
    if number.present?
      calPercent = number/5.to_f * 100
      # calPercent = number/10.to_f * 100
      #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
      percent = calPercent.round
      #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
      return percent.to_s
    else
      return 0
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/whites_helper.rb
module WhitesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inocchi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Silkscreen&display=swap" rel="stylesheet">
  </head>

  <body>
  <header>
  <h1>snow place</h1>
  <div class="header-list">
   <ul>
    <% if user_signed_in? %>
     <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
    <% else %>
     <li><%= link_to "Sign up", new_user_registration_path %></li>
     <li><%= link_to "Log in", new_user_session_path %></li>
    <% end %>
   </ul>
  </div>


  <div class="hamburger-menu">
        <input type="checkbox" id="menu-btn-check">
        <label for="menu-btn-check" class="menu-btn"><span></span></label>
        <div class="menu-content">
            <ul>
                <li>
                    <%= link_to "HOME", snows_path %>
                </li>
                <li>
                <%= link_to "NEW POST", new_snow_path %>
                </li>
                <li>
                <% if user_signed_in? %>
  <%= link_to "MYPAGE", user_path(current_user.id) %>
<% end %>
                </li>
                <li>
                <%= link_to "niigata", snows_niigata_path %>
                </li>
                <li>
                <%= link_to "nagano", snows_nagano_path %>
                </li>
                <li>
                <%= link_to "gunnma", snows_gunnma_path %>
                </li>
            </ul>
        </div>
    </div>


 </header>
 <main>
  <%= yield %>
 </main>
 <footer>
 <p> ©inocchi&akarin.</p>
</footer>

  </body>
</html>